# Generated by Django 4.2.4 on 2023-08-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
    ]
