# Generated by Django 4.2.4 on 2023-08-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj_app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='dj_app_blog_publish_a4942a_idx',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date='publish'),
        ),
    ]
